version: "3"
services:
  zimbra:
    #image: aashish9899/zimbra:v1
    build: .
    ports:
      - "25:25"
      - "80:80"
      - "443:443"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "7071:7071"
      - "8443:8443"
      - "9071:9071"
    hostname: mail.aashishlinux.tk
    volumes:
      - type: bind
        source: /opt/zimbra
        target: /opt/zimbra

    stdin_open: true
    tty: true
    restart: unless-stopped
